KatalogCvetov/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib import admin

from KatalogCvetov import views
from django.conf import settings

urlpatterns = patterns('',
    # ex: /polls/

    url(r'^$', views.index, name='index'),
    url(r'^test/', views.test, name='test'),
    url(r'^katalog/$', views.katalog, name='katalog'),
    url(r'^kontakti/$', views.kontakti, name='kontakti'),
    url(r'^onas/$', views.onas, name='onas'),
    url(r'^katalog/rastenie/(\d+)/$', views.rastenie, name='rastenie'),
    url(r'^katalog/vidrasteniya/(\d+)/$', views.vidrasteniya, name='vidrasteniya'),
    url(r'^katalogcvetov/ssilkirosteniy/(?P<katalogcvet_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<cvetok_id>\d+)/(?P<reyting_id>\d+)/(?P<kommentari_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<cvetikatalog_id>\d+)/vote/$', views.vote, name='vote'),
    # url(r'^katalogcvetov/ssilkirosteniy/$', views.ssilkirosteniy, name='ssilkirosteniy'),
    # ex: /polls/5/
    # ex: /polls/5/results/
    # ex: /polls/5/vote/

)

# from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

VodnieRozi/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'VodnieRozi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

     url(r'^', include('KatalogCvetov.urls', namespace='KatalogCvetov')),
     # url(r'^qwe/', include('KatalogCvetov.urls')),
    # url(r'^ssilkirosteniy/', include('KatalogCvetov.urls')),
     url(r'^admin/', include(admin.site.urls)),

)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

KatalogCvetov/models.py
#-*- coding: utf-8 -*-
from django.db import models
import datetime

# Создаем модели
class VidiRasteniy(models.Model):
    def __unicode__(self):
        return self.name_vida
    name_vida = models.CharField('Вид растения', max_length=200)
    class Meta(object):
        verbose_name = "Вид растения"
        verbose_name_plural = "Вид растения"


class CvetiKatalog(models.Model):
    """Клас модели цветка характеристики"""
    def __unicode__(self):
        return self.name_rosteniya
    #Переименовываем класс CvetiKatalog на русские названия
    class Meta(object):
        verbose_name = "Каталог цветов"
        verbose_name_plural = "Каталог цветов"
    #Переименовываем с латинского названия с помощью verbose_name="Виды растений"
    VidiRasteniy = models.ForeignKey(VidiRasteniy, verbose_name="Виды растений",related_name = 'cveti')
    name_rosteniya = models.CharField('Название цветка',max_length=200)
    cena = models.IntegerField('Цена',default=0,blank=True)
    opisanie = models.TextField('Описание',blank=True)
    coderjat = models.TextField('Содержание ростения',blank=True)
    polza = models.CharField('Польза ростения', max_length= 400,blank=True)
    sposob_razmnogeniya = models.CharField('Способ размножения',max_length=200,blank=True)
    peresadka = models.CharField('Пересадка',max_length=200,blank=True)
    osobennosty_uhod = models.CharField('Особенности ухода', max_length=200,blank=True)
    temperatera = models.CharField('Температура', max_length=200,blank=True)
    svet = models.CharField('Свет',max_length=200,blank=True)
    poliv = models.CharField('Полив', max_length=200,blank=True)
    vlajnost_vozduha = models.CharField('Влажность воздуха', max_length=200,blank=True)
    pochva = models.CharField('Почва', max_length=200,blank=True)
    pub_date = models.DateTimeField('Дата публикации',blank=True, default= datetime.datetime.now() )
    photo = models.ImageField(upload_to='preview/cveti',blank=True)


class PhotoView(models.Model):
    CvetiKatalog = models.ForeignKey(CvetiKatalog, verbose_name='Каталог цветов',related_name = 'photos')
    photo = models.ImageField('Фото',upload_to='preview/cveti',blank=True)
    # name_photo_view = models.CharField('Название фото',max_length=200)
    class Meta(object):
        verbose_name = "Фото растения"
        verbose_name_plural = "Фото растений"

class KommentariyCvetka(models.Model):
    #для нормального отображения имени класса в каталоге будет возвращать не KommentariyCvetka а сам комментарий
    def __unicode__(self):
        return self.kommentariy
    class Meta(object):
        verbose_name = "Комметарий"
        verbose_name_plural = "Комметарии"
    #end
    """
    Клас модели комментариев к цветку
    """
    CvetiKatalog = models.ForeignKey(CvetiKatalog, verbose_name='Каталог цветов')
    kommentariy = models.CharField('Комментарий ростения',max_length=200)

class ReytingCvetka(models.Model):
    def __unicode__(self):
         return ('Рейтинг растения: %s ' % self.reyting)
    class Meta(object):
        verbose_name = "Рейтинг растения"
        verbose_name_plural = "Рейтинги растиний"

    """
    Клас параметра "рейтиг" цветка интеджер
    """
    cveti_katalog = models.ForeignKey(CvetiKatalog, verbose_name= 'Каталог цветов')
    reyting = models.IntegerField('Рейтинг',default=0)

KatalogCvetov/views.py
# -*- coding: utf-8 -*-
from itertools import combinations
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from setuptools.command.sdist import re_finder
from KatalogCvetov.models import CvetiKatalog, ReytingCvetka, KommentariyCvetka, VidiRasteniy
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def test(request):
    KatalogCvetov = CvetiKatalog.objects.all()
    VidiRasteniySpisok = VidiRasteniy.objects.all()
    context = {'KatalogCvetov': KatalogCvetov, 'VidiRasteniySpisok': VidiRasteniySpisok}
    return render(request, 'katalogcvetov/test.html', context)


# def index(request):
#     latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
#     output = ', '.join([p.name_rosteniya for p in latest_katalogcvetov])
#     return HttpResponse('Последние 5-ть забитых ростений в каталог: %s.' % output)

def index(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/index.html', context)

def katalog(request):

    page = request.GET.get('page',False)
    poisk = request.GET.get('poisk',False)


    if (request.GET.get('sortvid', False)) and (request.GET.get('sortrost', False)) :
        sortvid = request.GET['sortvid']
        sortrost = request.GET['sortrost']
        page = request.GET.get('page',False)

        if (request.GET.get('vid', False)):

            if (sortvid == 'vidsortza') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk )
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortza'
                tekstvid = 'я-А'
                tekstrost ='А-я'


            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortaz'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya")
                sortvid = 'vidsortza'
                sortrost = 'rostensortaz'
                tekstvid = 'А-я'
                tekstrost ='я-А'

            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
                print('test')
                sortvid = 'vidsortza'
                sortrost = 'rostensortza'
                tekstvid = 'А-я'
                tekstrost ='А-я'

            elif (sortvid == 'vidsortza') and (sortrost == 'rostensortaz'):
                if (poisk):
                     cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)

                cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya")
                print('test')
                sortvid = 'vidsortaz'
                sortrost = 'rostensortaz'
                tekstvid = 'я-А'
                tekstrost ='я-А'


        if (request.GET.get('rost', False)):

            if (sortvid == 'vidsortza') and (sortrost == 'rostensortza'):

                cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya")

                if (poisk):
                    cveti_katalog_list = cveti_katalog_list.filter(name_rosteniya__icontains = poisk)


                sortvid = 'vidsortza'
                sortrost = 'rostensortaz'
                tekstvid = 'А-я'
                tekstrost = 'я-А'


            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortaz'):
                if(poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortza'
                tekstvid = 'я-А'
                tekstrost = 'А-я'

            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortaz'
                tekstvid = 'я-А'
                tekstrost = 'я-А'

            elif (sortvid == 'vidsortza') and (sortrost == 'rostensortaz'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortza'
                sortrost = 'rostensortza'
                tekstvid = 'А-я'
                tekstrost = 'А-я'

    else:
        # KatalogCvetov = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
        if (poisk):
            cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
        else:
            cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
        sortvid = 'vidsortza'
        sortrost = 'rostensortza'
        tekstvid = 'А-я'
        tekstrost ='А-я'
        print('test3')
    # print(cveti_katalog_list[0].coderjat)

    paginator = Paginator(cveti_katalog_list, 2) # показывать 25 растений на странице

    page = request.GET.get('page')
    try:
        KatalogCvetov = paginator.page(page)
    except PageNotAnInteger:
        # если страница не целое число то вызывается первая страница
        KatalogCvetov = paginator.page(1)
        page = 1
    except EmptyPage:
        # Если указанной страницы нет то открывается последняя страница
        KatalogCvetov = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    context = locals()
    # print(context['vidsort'],789)
    # context = {'KatalogCvetov': KatalogCvetov, 'VidiRasteniySpisok': VidiRasteniySpisok, 'sortinvert': sortinvert}
    return render(request, 'katalogcvetov/katalog.html', context)


def vidrasteniya(request, id_vid_rost):
    vid = VidiRasteniy.objects.get(id=id_vid_rost)
    # проверяем если есть переменая то идем дальше по условиям, ее переменной нет то заменяес сс на False
    # и идем в else
    if request.GET.get('sort', False):
        sortget = request.GET['sort']
        if sortget == 'za':
            sortinvert = ''
            KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("-name_rosteniya")

        elif sortget == '':
            sortinvert = 'za'
            KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("name_rosteniya")

    else:
        sortinvert = 'za'
        KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("name_rosteniya")


    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    id_vida = id_vid_rost
    # штука ниже  собирает все в локальные переменные
    context = locals()
    # context = {'KatalogCvetov':KatalogCvetov,'VidiRasteniySpisok':VidiRasteniySpisok,'id_vida':id_vida,'sortinvert':sortinvert}
    return render(request, 'katalogcvetov/vidrasteniya.html', context)


def rastenie(request, id_rast):
    Rastenie = CvetiKatalog.objects.get(id=id_rast)
    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    RasteniePhoto = Rastenie.photos.all()
    context = {'Rastenie': Rastenie, 'VidiRasteniySpisok': VidiRasteniySpisok, 'RasteniePhoto': RasteniePhoto}
    return render(request, 'katalogcvetov/rastenie.html', context)


def kontakti(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/kontakti.html', context)


def onas(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/onas.html', context)


# Сложная функця  запроса  ниже убдет приведена аналогичная но проще
# def ssilkirosteniy(request):
#     latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
#     templates = loader.get_template('katalogcvetov/index.html')
#     context = RequestContext(request,{'latest_katalogcvetov':latest_katalogcvetov,})
#     return HttpResponse(templates.render(context))
def ssilkirosteniy(request):
    latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
    context = {'latest_katalogcvetov': latest_katalogcvetov}
    return render(request, 'katalogcvetov/index.html', context)



def detail(request, katalogcvet_id):
    # try:
    #     cvetikatalog = CvetiKatalog.objects.get(pk = katalogcvet_id)
    # except CvetiKatalog.DoesNotExist:
    #     raise Http404 ('Нет такого ростения')

KatalogCvetov/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {#подклюяаю шрифт от гугла для шапки    #}
    <link href='http://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto:500,900italic,900,400italic,100,700italic,300,700,500italic,100italic,300italic,400&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
    {#<--Статичный файлы начало-->#}
    {% load staticfiles %}
    <meta charset="UTF-8">
    <title>Сайт проба</title>
    {#    <link rel="stylesheet" href="{% static 'katalogcvetov/css/bootstrap.css' %}"/>#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'katalogcvetov/css/custom.css' %}"/>#}
    {#    <script src="{% static 'katalogcvetov/js/jquery-1.11.3.min.js' %}"></script>#}
    {#    <script src="{% static 'katalogcvetov/js/bootstrap.js' %}"></script>#}
    {#    <link rel="stylesheet" type="text/css" href="{% static 'katalogcvetov/css/bootstrap.css' %}"/>#}
    <link rel="stylesheet" type="text/css" href="{% static 'katalogcvetov/css/proba.css' %}"/>
    {% block static %}

    {% endblock %}
    <!--Статичный файлы конец-->
</head>
<body>
<!--Сайт начало-->
<div class="container">
    <!--Шапка начало-->
    <div class="shapka">
        <a class=".shapka_logo_silka" href="{% url 'KatalogCvetov:index' %}">
            <div class="shapka_logo"></div>
        </a>

        <div class="shapka_kont"><a href="#">Телефон: 8(3452)99-99-99</a></div>
        <div class="shapka_text"><a href="{% url 'KatalogCvetov:katalog' %}">Растения под заказ</a></div>


    </div>
    <!--Шапка конец-->
    <!--Главное меню начало-->
    <div class="top_menu_btn"> <!-- блок-обертка для меню -->
        {#        <ul>#}
        {#            <li><a href="{% url 'KatalogCvetov:index' %}">Главная</a></li>#}
        {#            <li><a href="{% url 'KatalogCvetov:katalog' %}">Каталог</a></li>#}
        {#            <li><a href="{% url 'KatalogCvetov:kontakti' %}">Контакты</a></li>#}
        {#            <li><a href="{% url 'KatalogCvetov:onas' %}">О нас</a></li>#}
        {#            <li class="poisk">#}
        {#                <div>#}
        {#                    <form action="{% url 'KatalogCvetov:katalog' %}" method="get">#}
        {##}
        {#                        <input type="text" name="poisk" placeholder="Поиск">#}
        {#                        <input type="submit" value="Поиск">#}
        {#                    </form>#}
        {#                </div>#}
        {#            </li>#}
        {#        </ul>#}
        <div class="menu_top">
            <div class="menu_tp"><a href="{% url 'KatalogCvetov:index' %}">Главная</a></div>
            <div class="menu_tp"><a href="{% url 'KatalogCvetov:katalog' %}">Каталог</a></div>
            <div class="menu_tp"><a href="{% url 'KatalogCvetov:kontakti' %}">Контакты</a></div>
            <div class="menu_tp" _><a href="{% url 'KatalogCvetov:onas' %}">О нас</a></div>

        </div>
        <div class="poisk">
            <form action="{% url 'KatalogCvetov:katalog' %}" method="get">
                <input type="text" name="poisk" placeholder="Поиск">
                <input type="submit" value="Поиск">
            </form>
        </div>


    </div>
    <!--Главное меню конец-->
    {% block content_inf %}
        <div class="content">
            <!--Левая колонка начало-->
            <div class="kol_left">
                <div class="kol_left_visota">
                    {% block kol_left %}

                    {% endblock %}
                </div>
            </div>
            <!--Левая колонка конец-->
            <!--Правая колонка начало-->
            <div class="kol_right">
                {% block right %}

                {% endblock %}
            </div>
            <!--Правая колонка конец-->

        </div>
    {% endblock %}
    <!--Футер начало-->
    <div class="footer">
        <ul>
            <li><a href="#">почта:</a></li>
            <li><a href="#">права:</a></li>
            <!--счетчик яндекс начало-->
            <li>
                <a href="#">
                    <!-- Yandex.Metrika informer -->
                    <a href="https://metrika.yandex.ru/stat/?id=31423873&amp;from=informer"
                       target="_blank" rel="nofollow"><img
                            src="https://mc.yandex.ru/informer/31423873/3_1_FFFFB9FF_FFFF99FF_0_pageviews"
                            style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика"
                            title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"
                            onclick="try{Ya.Metrika.informer({i:this,id:31423873,lang:'ru'});return false}catch(e){}"/></a>
                    <!-- /Yandex.Metrika informer -->

                    <!-- Yandex.Metrika counter -->
                    <script type="text/javascript">
                        (function (d, w, c) {
                            (w[c] = w[c] || []).push(function () {
                                try {
                                    w.yaCounter31423873 = new Ya.Metrika({
                                        id: 31423873,
                                        clickmap: true,
                                        trackLinks: true,
                                        accurateTrackBounce: true
                                    });
                                } catch (e) {
                                }
                            });

                            var n = d.getElementsByTagName("script")[0],
                                    s = d.createElement("script"),
                                    f = function () {
                                        n.parentNode.insertBefore(s, n);
                                    };
                            s.type = "text/javascript";
                            s.async = true;
                            s.src = "https://mc.yandex.ru/metrika/watch.js";

                            if (w.opera == "[object Opera]") {
                                d.addEventListener("DOMContentLoaded", f, false);
                            } else {
                                f();
                            }
                        })(document, window, "yandex_metrika_callbacks");
                    </script>
                    <noscript>
                        <div><img src="https://mc.yandex.ru/watch/31423873" style="position:absolute; left:-9999px;"
                                  alt=""/></div>
                    </noscript>
                    <!-- /Yandex.Metrika counter -->
                </a>
            </li>

            <!--счетчик яндекс коенц-->
        </ul>
    </div>
    <!--Футер конец-->
</div>



{% block content %}

{% endblock %}
<!--Сайт конец-->
</div>
</body>
</html>

{#!!! Набираем например ul  и жмем клавишу Tab на клавиатере !!!#}
{# emmit  http://emmet.io/#}
{#http://docs.emmet.io/cheat-sheet/#}
{#span{s;lsfke;sksk;l}#}
{#.roma>span.roma2>table#}
{#span*3#}
{#ul>li.dsa$*10#}
{#ul>li.dsa$$$*10#}
{#ul>li.dsa$@5*10#}
{#ul>li.dsa$@-*10#}