KatalogCvetov/urls.py
#-*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from django.contrib import admin

from KatalogCvetov import views
from django.conf import settings

urlpatterns = patterns('',
    # ex: /polls/

    url(r'^$', views.index, name='index'),
    url(r'^test/', views.test, name='test'),
    url(r'^katalog/$', views.katalog, name='katalog'),
    url(r'^kontakti/$', views.kontakti, name='kontakti'),
    url(r'^onas/$', views.onas, name='onas'),
    url(r'^katalog/rastenie/(\d+)/$', views.rastenie, name='rastenie'),
    url(r'^katalog/vidrasteniya/(\d+)/$', views.vidrasteniya, name='vidrasteniya'),
    url(r'^katalogcvetov/ssilkirosteniy/(?P<katalogcvet_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<cvetok_id>\d+)/(?P<reyting_id>\d+)/(?P<kommentari_id>\d+)/results/$', views.results, name='results'),
    url(r'^(?P<cvetikatalog_id>\d+)/vote/$', views.vote, name='vote'),
    # url(r'^katalogcvetov/ssilkirosteniy/$', views.ssilkirosteniy, name='ssilkirosteniy'),
    # ex: /polls/5/
    # ex: /polls/5/results/
    # ex: /polls/5/vote/

)

# from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

VodnieRozi/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'VodnieRozi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

     url(r'^', include('KatalogCvetov.urls', namespace='KatalogCvetov')),
     # url(r'^qwe/', include('KatalogCvetov.urls')),
    # url(r'^ssilkirosteniy/', include('KatalogCvetov.urls')),
     url(r'^admin/', include(admin.site.urls)),

)

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

KatalogCvetov/models.py
#-*- coding: utf-8 -*-
from django.db import models
import datetime

# Создаем модели
class VidiRasteniy(models.Model):
    def __unicode__(self):
        return self.name_vida
    name_vida = models.CharField('Вид растения', max_length=200)
    class Meta(object):
        verbose_name = "Вид растения"
        verbose_name_plural = "Вид растения"


class CvetiKatalog(models.Model):
    """Клас модели цветка характеристики"""
    def __unicode__(self):
        return self.name_rosteniya
    #Переименовываем класс CvetiKatalog на русские названия
    class Meta(object):
        verbose_name = "Каталог цветов"
        verbose_name_plural = "Каталог цветов"
    #Переименовываем с латинского названия с помощью verbose_name="Виды растений"
    VidiRasteniy = models.ForeignKey(VidiRasteniy, verbose_name="Виды растений",related_name = 'cveti')
    name_rosteniya = models.CharField('Название цветка',max_length=200)
    cena = models.IntegerField('Цена',default=0,blank=True)
    opisanie = models.TextField('Описание',blank=True)
    coderjat = models.TextField('Содержание ростения',blank=True)
    polza = models.CharField('Польза ростения', max_length= 400,blank=True)
    sposob_razmnogeniya = models.CharField('Способ размножения',max_length=200,blank=True)
    peresadka = models.CharField('Пересадка',max_length=200,blank=True)
    osobennosty_uhod = models.CharField('Особенности ухода', max_length=200,blank=True)
    temperatera = models.CharField('Температура', max_length=200,blank=True)
    svet = models.CharField('Свет',max_length=200,blank=True)
    poliv = models.CharField('Полив', max_length=200,blank=True)
    vlajnost_vozduha = models.CharField('Влажность воздуха', max_length=200,blank=True)
    pochva = models.CharField('Почва', max_length=200,blank=True)
    pub_date = models.DateTimeField('Дата публикации',blank=True, default= datetime.datetime.now() )
    photo = models.ImageField(upload_to='preview/cveti',blank=True)


class PhotoView(models.Model):
    CvetiKatalog = models.ForeignKey(CvetiKatalog, verbose_name='Каталог цветов',related_name = 'photos')
    photo = models.ImageField('Фото',upload_to='preview/cveti',blank=True)
    # name_photo_view = models.CharField('Название фото',max_length=200)
    class Meta(object):
        verbose_name = "Фото растения"
        verbose_name_plural = "Фото растений"

class KommentariyCvetka(models.Model):
    #для нормального отображения имени класса в каталоге будет возвращать не KommentariyCvetka а сам комментарий
    def __unicode__(self):
        return self.kommentariy
    class Meta(object):
        verbose_name = "Комметарий"
        verbose_name_plural = "Комметарии"
    #end
    """
    Клас модели комментариев к цветку
    """
    CvetiKatalog = models.ForeignKey(CvetiKatalog, verbose_name='Каталог цветов')
    kommentariy = models.CharField('Комментарий ростения',max_length=200)

class ReytingCvetka(models.Model):
    def __unicode__(self):
         return ('Рейтинг растения: %s ' % self.reyting)
    class Meta(object):
        verbose_name = "Рейтинг растения"
        verbose_name_plural = "Рейтинги растиний"

    """
    Клас параметра "рейтиг" цветка интеджер
    """
    cveti_katalog = models.ForeignKey(CvetiKatalog, verbose_name= 'Каталог цветов')
    reyting = models.IntegerField('Рейтинг',default=0)

KatalogCvetov/views.py
# -*- coding: utf-8 -*-
from itertools import combinations
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from setuptools.command.sdist import re_finder
from KatalogCvetov.models import CvetiKatalog, ReytingCvetka, KommentariyCvetka, VidiRasteniy
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def test(request):
    KatalogCvetov = CvetiKatalog.objects.all()
    VidiRasteniySpisok = VidiRasteniy.objects.all()
    context = {'KatalogCvetov': KatalogCvetov, 'VidiRasteniySpisok': VidiRasteniySpisok}
    return render(request, 'katalogcvetov/test.html', context)


# def index(request):
#     latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
#     output = ', '.join([p.name_rosteniya for p in latest_katalogcvetov])
#     return HttpResponse('Последние 5-ть забитых ростений в каталог: %s.' % output)

def index(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/index.html', context)

def katalog(request):

    page = request.GET.get('page',False)
    poisk = request.GET.get('poisk',False)


    if (request.GET.get('sortvid', False)) and (request.GET.get('sortrost', False)) :
        sortvid = request.GET['sortvid']
        sortrost = request.GET['sortrost']
        page = request.GET.get('page',False)

        if (request.GET.get('vid', False)):

            if (sortvid == 'vidsortza') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk )
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortza'
                tekstvid = 'я-А'
                tekstrost ='А-я'


            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortaz'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya")
                sortvid = 'vidsortza'
                sortrost = 'rostensortaz'
                tekstvid = 'А-я'
                tekstrost ='я-А'

            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
                print('test')
                sortvid = 'vidsortza'
                sortrost = 'rostensortza'
                tekstvid = 'А-я'
                tekstrost ='А-я'

            elif (sortvid == 'vidsortza') and (sortrost == 'rostensortaz'):
                if (poisk):
                     cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)

                cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya")
                print('test')
                sortvid = 'vidsortaz'
                sortrost = 'rostensortaz'
                tekstvid = 'я-А'
                tekstrost ='я-А'


        if (request.GET.get('rost', False)):

            if (sortvid == 'vidsortza') and (sortrost == 'rostensortza'):

                cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "-name_rosteniya")

                if (poisk):
                    cveti_katalog_list = cveti_katalog_list.filter(name_rosteniya__icontains = poisk)


                sortvid = 'vidsortza'
                sortrost = 'rostensortaz'
                tekstvid = 'А-я'
                tekstrost = 'я-А'


            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortaz'):
                if(poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortza'
                tekstvid = 'я-А'
                tekstrost = 'А-я'

            elif (sortvid == 'vidsortaz') and (sortrost == 'rostensortza'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("-VidiRasteniy__name_vida", "-name_rosteniya")
                sortvid = 'vidsortaz'
                sortrost = 'rostensortaz'
                tekstvid = 'я-А'
                tekstrost = 'я-А'

            elif (sortvid == 'vidsortza') and (sortrost == 'rostensortaz'):
                if (poisk):
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
                else:
                    cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
                sortvid = 'vidsortza'
                sortrost = 'rostensortza'
                tekstvid = 'А-я'
                tekstrost = 'А-я'

    else:
        # KatalogCvetov = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
        if (poisk):
            cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya").filter(name_rosteniya__icontains = poisk)
        else:
            cveti_katalog_list = CvetiKatalog.objects.all().order_by("VidiRasteniy__name_vida", "name_rosteniya")
        sortvid = 'vidsortza'
        sortrost = 'rostensortza'
        tekstvid = 'А-я'
        tekstrost ='А-я'
        print('test3')
    # print(cveti_katalog_list[0].coderjat)

    paginator = Paginator(cveti_katalog_list, 2) # показывать 25 растений на странице

    page = request.GET.get('page')
    try:
        KatalogCvetov = paginator.page(page)
    except PageNotAnInteger:
        # если страница не целое число то вызывается первая страница
        KatalogCvetov = paginator.page(1)
        page = 1
    except EmptyPage:
        # Если указанной страницы нет то открывается последняя страница
        KatalogCvetov = paginator.page(paginator.num_pages)
        page = paginator.num_pages
    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    context = locals()
    # print(context['vidsort'],789)
    # context = {'KatalogCvetov': KatalogCvetov, 'VidiRasteniySpisok': VidiRasteniySpisok, 'sortinvert': sortinvert}
    return render(request, 'katalogcvetov/katalog.html', context)


def vidrasteniya(request, id_vid_rost):
    vid = VidiRasteniy.objects.get(id=id_vid_rost)
    # проверяем если есть переменая то идем дальше по условиям, ее переменной нет то заменяес сс на False
    # и идем в else
    if request.GET.get('sort', False):
        sortget = request.GET['sort']
        if sortget == 'za':
            sortinvert = ''
            KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("-name_rosteniya")

        elif sortget == '':
            sortinvert = 'za'
            KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("name_rosteniya")

    else:
        sortinvert = 'za'
        KatalogCvetov = CvetiKatalog.objects.filter(VidiRasteniy=vid).order_by("name_rosteniya")


    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    id_vida = id_vid_rost
    # штука ниже  собирает все в локальные переменные
    context = locals()
    # context = {'KatalogCvetov':KatalogCvetov,'VidiRasteniySpisok':VidiRasteniySpisok,'id_vida':id_vida,'sortinvert':sortinvert}
    return render(request, 'katalogcvetov/vidrasteniya.html', context)


def rastenie(request, id_rast):
    Rastenie = CvetiKatalog.objects.get(id=id_rast)
    VidiRasteniySpisok = VidiRasteniy.objects.all().order_by("name_vida")
    RasteniePhoto = Rastenie.photos.all()
    context = {'Rastenie': Rastenie, 'VidiRasteniySpisok': VidiRasteniySpisok, 'RasteniePhoto': RasteniePhoto}
    return render(request, 'katalogcvetov/rastenie.html', context)


def kontakti(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/kontakti.html', context)


def onas(request):
    context = {'': ''}
    return render(request, 'katalogcvetov/onas.html', context)


# Сложная функця  запроса  ниже убдет приведена аналогичная но проще
# def ssilkirosteniy(request):
#     latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
#     templates = loader.get_template('katalogcvetov/index.html')
#     context = RequestContext(request,{'latest_katalogcvetov':latest_katalogcvetov,})
#     return HttpResponse(templates.render(context))
def ssilkirosteniy(request):
    latest_katalogcvetov = CvetiKatalog.objects.order_by('pub_date')[:5]
    context = {'latest_katalogcvetov': latest_katalogcvetov}
    return render(request, 'katalogcvetov/index.html', context)



def detail(request, katalogcvet_id):
    # try:
    #     cvetikatalog = CvetiKatalog.objects.get(pk = katalogcvet_id)
    # except CvetiKatalog.DoesNotExist:
    #     raise Http404 ('Нет такого ростения')

KatalogCvetov/templates/katalogcvetov/index.html
{% extends "base.html" %}

{% block content_inf %}
    <div class="content_inf">
        <div class="kontakt">
            <div class="inf_1">Контакты</div>
            <div class="inf">г. Тюмень, ул. Холодильная, 65/7</div>
            <div class="inf">Торговый ряд «На Холодильной»</div>
            <div class="inf">Телефон: +7 (3452) 60-20-68</div>
            <div class="inf">Эл. почта: <a href="mailto:order@2400.ru">order@2400.ru</a></div>
            <div class="inf">ICQ: 236544786</div>
            <div class="inf">Время работы Салона: ежедневно с 08:00 до 20:00</div>
            <div class="inf_foto"><script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=gRmrSBPHf8NYO5Pvvod573dfgGXKYPBE&width=600&height=450"></script></div>

        </div>
    </div>
{% endblock %}

KatalogCvetov/templates/katalogcvetov/katalog.html
{% extends "base.html" %}


{% block kol_left %}

    <ul>
        {% for vidirasteniy in VidiRasteniySpisok %}
            <li><a href="{% url 'KatalogCvetov:vidrasteniya' vidirasteniy.id %}">{{ vidirasteniy.name_vida }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

{% block right %}
    <div class="kol_right">
        <div class="sort">
            <div class="sort1"><a href="{% url 'KatalogCvetov:katalog' %}?vid=vid&sortvid={{ sortvid }}&sortrost={{ sortrost }}&page={{ page }}">По видам {{ tekstvid }}</a></div>
            <div class="sort1"><a href="{% url 'KatalogCvetov:katalog' %}?rost=rost&sortvid={{ sortvid }}&sortrost={{ sortrost }}&page={{ page }}">По ростениям {{ tekstrost }}</a></div>
        </div>
        {% if KatalogCvetov %}
            <div class="katalog_cvetov">
                {#                Группируем растения по виду растений#}
                {% regroup KatalogCvetov by VidiRasteniy as vidirasteniy_list %}
                {% for VidiRasteniy in vidirasteniy_list %}
                    <div class="stroka0">
                        {#                      выводим вид растений#}
                        {{ VidiRasteniy.grouper }}
                    </div>
                    {#                    Выводим все растения конкретного вида#}
                    {% for rastenie in VidiRasteniy.list %}
                        <div class="stroka1">
                            <div class="pole1">
                                <a href="{% url 'KatalogCvetov:rastenie' rastenie.id %}">{{ rastenie.name_rosteniya }}</a>
                            </div>
                            <div class="pole2"><a
                                    href="{% url 'KatalogCvetov:rastenie' rastenie.id %}">{{ rastenie.cena }}р.</a>
                            </div>
                            <div class="pole3"><a href="{% url 'KatalogCvetov:rastenie' rastenie.id %}">
                                <img src="{{ MEDIA_URL }}{{ rastenie.photo }}" height="100" width="100"/>
                            </a></div>
                        </div>
                    {% endfor %}
                {% endfor %}
            </div>
        {% else %}
            <p>нет информации</p>
        {% endif %}
        <div class="sort">
            <div class="sort1"><a href="{% url 'KatalogCvetov:katalog' %}?vid=vid&sortvid={{ sortvid }}&sortrost={{ sortrost }}&page={{ page }}">По видам {{ tekstvid }}</a></div>
            <div class="sort1"><a href="{% url 'KatalogCvetov:katalog' %}?rost=rost&sortvid={{ sortvid }}&sortrost={{ sortrost }}&page={{ page }}">По ростениям {{ tekstrost }}</a></div>
        </div>

        <div class="str">
            <div class="pagination">
            <span class="step-links">
             {% if KatalogCvetov.has_previous %}
                <a href="{% url 'KatalogCvetov:katalog' %}?page={{ KatalogCvetov.previous_page_number }}">Назад</a>
            {% endif %}

            <span class="current">
            Страница {{ KatalogCvetov.number }} из {{ KatalogCvetov.paginator.num_pages }}.
            </span>

            {% if KatalogCvetov.has_next %}
                <a href="{% url 'KatalogCvetov:katalog' %}?page={{ KatalogCvetov.next_page_number }}&sortvid={{ sortvid }}$ sortrost={{ sortrost }}">вперед</a>
            {% endif %}
                </span>
            </div>
        </div>


    </div>
{% endblock %}





{#!!! Набираем например ul  и жмем клавишу Tab на клавиатере !!!#}
{# emmit  http://emmet.io/#}
{#http://docs.emmet.io/cheat-sheet/#}
{#span{s;lsfke;sksk;l}#}
{#.roma>span.roma2>table#}
{#span*3#}
{#ul>li.dsa$*10#}
{#ul>li.dsa$$$*10#}
{#ul>li.dsa$@5*10#}
{#ul>li.dsa$@-*10#}

KatalogCvetov/templates/katalogcvetov/rastenie.html
{% extends "base.html" %}

{#левый блок начало!!!#}
{% block kol_left %}
    <ul>
        {% for vidirasteniy in VidiRasteniySpisok %}
            <li><a href="{% url 'KatalogCvetov:vidrasteniya' vidirasteniy.id %}">{{ vidirasteniy.name_vida }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}
{#левый блок конец!!!#}

{#правый блок начало!!!#}
{% block right %}
    {% if Rastenie %}
        <div class="katalog_cvetov">
            <div class="stroka">
                <div class="pole_cont_name1">
                    {{ Rastenie.name_rosteniya }}
                </div>
                <div class="foto">
                    {% if Rastenie.photo %}
                        <div class="pole_cont_foto">
                            <img src="{{ MEDIA_URL }}{{ Rastenie.photo }}" height="200" width="200"/>
                        </div>
                    {% endif %}
                    {% if RasteniePhoto %}
                        {% for fotorasteniya in RasteniePhoto %}
                            <div class="pole_cont_foto">
                                <img src="{{ MEDIA_URL }}{{ fotorasteniya.photo }}" height="200" width="200"/>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
                {% if Rastenie.opisanie %}
                    <div class="pole_cont_name2">
                        <div class="abzac">Описание:</div>
                        {{ Rastenie.opisanie }}</div>
                {% endif %}
                {% if Rastenie.coderjat %}
                    <div class="pole_cont_name3">
                        <div class="abzac">Характиристика:</div>
                        {{ Rastenie.coderjat }}</div>
                {% endif %}
                {% if Rastenie.polza %}
                    <div class="pole_cont_name4">
                        <div class="abzac">Польза растения:</div>
                        {{ Rastenie.polza }}</div>
                {% endif %}
                {% if Rastenie.sposob_razmnogeniya %}
                    <div class="pole_cont_name5">
                        <div class="abzac">Способ размножения:</div>
                        {{ Rastenie.sposob_razmnogeniya }}</div>
                {% endif %}
                {% if Rastenie.peresadka %}
                    <div class="pole_cont_name6">
                        <div class="abzac">Пересадка:</div>
                        {{ Rastenie.peresadka }}</div>
                {% endif %}
                {% if Rastenie.osobennosty_uhod %}
                    <div class="pole_cont_name7">
                        <div class="abzac">Особенности ухода:</div>
                        {{ Rastenie.osobennosty_uhod }}</div>
                {% endif %}
                {% if Rastenie.temperatera %}
                    <div class="pole_cont_name8">
                        <div class="abzac">Температура:</div>
                        {{ Rastenie.temperatera }}</div>
                {% endif %}
                {% if Rastenie.svet %}
                    <div class="pole_cont_name9">
                        <div class="abzac">Свет:</div>
                        {{ Rastenie.svet }}</div>
                {% endif %}
                {% if Rastenie.poliv %}
                    <div class="pole_cont_name10">
                        <div class="abzac">Полив:</div>
                        {{ Rastenie.poliv }}</div>
                {% endif %}
                {% if Rastenie.vlajnost_vozduha %}
                    <div class="pole_cont_name11">
                        <div class="abzac">Влажность воздуха:</div>
                        {{ Rastenie.vlajnost_vozduha }}</div>
                {% endif %}
                {% if Rastenie.pochva %}
                    <div class="pole_cont_name12">
                        <div class="abzac">Почва:</div>
                        {{ Rastenie.pochva }}</div>
                {% endif %}
                {% if Rastenie.cena %}
                    <div class="pole_cont_cena">
                        <div class="abzac">Цена:</div>
                        {{ Rastenie.cena }}р.
                    </div>
                {% endif %}
            </div>
        </div>
    {% else %}
        <p>нет информации</p>
    {% endif %}
{% endblock %}
{#правый блок конец!!!#}

{#!!! Набираем например ul  и жмем клавишу Tab на клавиатере !!!#}
{# emmit  http://emmet.io/#}
{#http://docs.emmet.io/cheat-sheet/#}
{#span{s;lsfke;sksk;l}#}
{#.roma>span.roma2>table#}
{#span*3#}
{#ul>li.dsa$*10#}
{#ul>li.dsa$$$*10#}
{#ul>li.dsa$@5*10#}
{#ul>li.dsa$@-*10#}

KatalogCvetov/templates/katalogcvetov/vidrasteniya.html
{% extends "base.html" %}


{% block kol_left %}

    <ul>
        {% for vidirasteniy in VidiRasteniySpisok %}
            <li><a href="{% url 'KatalogCvetov:vidrasteniya' vidirasteniy.id %}">{{ vidirasteniy.name_vida }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

{% block right %}
    <div class="kol_right">
        <div class="sort">
            <div class="sort1"><a href="{% url 'KatalogCvetov:vidrasteniya' id_vida  %}?sort={{ sortinvert }}">А-я</a></div>
        </div>
        {% if KatalogCvetov %}
            <div class="katalog_cvetov">
                <div class="stroka0">{{ vid }}</div>
                {% for katalog in KatalogCvetov %}
                    <div class="stroka1">
                        <div class="pole1">
                            <a href="{% url 'KatalogCvetov:rastenie' katalog.id %}">{{ katalog.name_rosteniya }}</a>
                        </div>
                        <div class="pole2"><a
                                href="{% url 'KatalogCvetov:rastenie' katalog.id %}">{{ katalog.cena }}р.</a>
                        </div>
                        <div class="pole3"><a href="{% url 'KatalogCvetov:rastenie' katalog.id %}">
                            <img src="{{ MEDIA_URL }}{{ katalog.photo }}" height="100" width="100"/>
                        </a></div>
                    </div>
                {% endfor %}

            </div>
        {% else %}
            <p>нет информации</p>
        {% endif %}
        <div class="sort">
{#            <div class="sort1"><a href="{% url 'KatalogCvetov:katalogrostza' %}">А-я</a></div>#}
        </div>
    <div class="sort">
            <div class="sort1"><a href="{% url 'KatalogCvetov:vidrasteniya' id_vida  %}?sort={{ sortinvert }}">А-я</a></div>
        </div>
    </div>

{% endblock %}





{#!!! Набираем например ul  и жмем клавишу Tab на клавиатере !!!#}
{# emmit  http://emmet.io/#}
{#http://docs.emmet.io/cheat-sheet/#}
{#span{s;lsfke;sksk;l}#}
{#.roma>span.roma2>table#}
{#span*3#}
{#ul>li.dsa$*10#}
{#ul>li.dsa$$$*10#}
{#ul>li.dsa$@5*10#}
{#ul>li.dsa$@-*10#}